---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
matrix(c(1,2,3,4),2,2)
matrix(c(1,2,3,4),2,2,byrow=0)
matrix(1:10,5,5)
diag(1,5,5)
diag(1:5,5,5)
#matriz inversa
C=matrix(c(2,5,3,7),2,2)
solve(C)
det(C)
#opercaciones de matrices
A=matrix(c(1,2,3,4),2,2)
A%*%C
t(C)
d=C%*%t(C)
C%*%solve(C)
eigen(d)
svd(d)
qr(d)
#dimencion
dim(d)
```

#ARRAYS genealizacion

```{r}
array(1:81,c(3,3,3,3))
```
#heterogeneas
Estas estructuras permiten el uso de diferentes tipos u clase su objetos
* dataframes (base de datos)
tiene una estructura similar a una metriz 
```{r}
id=1:8
name=c("adriana","anahi","miguel","rayner","rebeca","sergio","vania","yoselin")
mujer<-c(1,1,0,0,1,0,1,1)
bd<-data.frame(id,name,mujer)
bd

dim(bd)
str(bd)
```



```{r}
#vectores
x=1:100
x[c(1,5,7)]
x[-c(1,5,7)]
o=(x%%2)==0
x2=c(2,3,4,5)
X2[T,T,F,F]
#matrices
AA=matrix(1:30,5,6)
AA[3,4]
AA[,-c(1:2)]
AA[3:4,c(1,3)]
AA[c(T,T,T,F,F),c(T,F,T,F,F,F)]
bd[1:6,c("name","id")]
bd[,-c(3)]
mean(bd$mujer)  
bd[bd$edad<=21,]



```




```{r}
#importacion de datos 
getwd()
dir()

setwd("C:/Users/rebal/Desktop/Nueva carpeta")
mun15=read.csv("municipales2015.csv")
library(foreign)
bd12p=read.dta("DBvivienda2012vf_9.dta")
bd12p
#exportar la base de datos 
##otros formatos
##RData
write.csv(bd12p,"bd12p.csv")
save(mun15,bd12p,file="bases.RDate")
rm(list=ls())

load
actividad para el dia martes 


```
clase 9/03/2001
```{r}
install.packages("dplyr")
library(dplyr)
install.packages(("rlang"))
rm(list=ls())
load(url("https://github.com/AlvaroLimber/EST-383/raw/master/data/eh19.RData"))
#computo 9 marzo
setwd("C:\\Users\\rebal\\Desktop\\bases dedatos")
bd=read.csv("lp_2021.csv",sep="|", header=T)
dir()
names(bd)
names(eh19p)
attributes(bd)
ehvat=attributes(eh19p)
head(bd)
tail(bd)
View(bd)
head(eh19p)
View(eh19p)
View(bd)
#R base
names(eh19p)[5]<-"sexo"
#dplyr "anidar acciones" pipeline %>%
eh19p %>% rename(edad=s02a_03)


```

